[book]
language = "en"
multilingual = true
src = "src"
title = "Breez SDK - Nodeless"

[output.html]
theme = "theme"
additional-css = ["styles.css"]
additional-js = ["tabs.js"]
git-repository-url = "https://github.com/breez/breez-sdk-liquid-docs"
edit-url-template = "https://github.com/breez/breez-sdk-liquid-docs/edit/main/{path}"
no-section-label = true

[output.html.fold]
enable = true

[output.html.print]
enable = false

[preprocessor.snippets]
after = ["links"]

[preprocessor.variables.variables]
api_key_form_uri = "https://breez.technology/request-api-key/#contact-us-form-sdk"
